
server:
  port: 7074
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/navneet
    username: root
    password: Movie@Don1645
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /api4
  boot:
   admin:
     client:
       url: http://localhost:1111/      
management:
  endpoints:
    web:
      exposure:
        include: '*'
